name: gmap_flutter
description: Customized Google Map In Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.2.4
  google_maps_flutter_web: ^0.4.0+6
  dio: ^5.0.1
  connectivity_plus: ^3.0.3
  location: ^4.4.0
  permission_handler: ^10.2.0
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  fluster: ^1.2.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/style/
    - assets/marker/
    - assets/placeholder/
